title: SOL MEDIA LAB Inc.
url: "https://solmelab.com"
baseurl: ""

collections:
  portfolio:
    output: true
    permalink: /portfolio/:slug/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio

exclude:
  - README.md

sass:
  quiet_deps: true
