backend:
  name: github
  repo: hongbj123-create/sol-medialab-site
  branch: main
  base_url: https://decap-oauth-proxy-one.vercel.app
  auth_endpoint: api/auth

media_folder: "assets/img/portfolio"
public_folder: "/assets/img/portfolio"

publish_mode: simple

collections:
  - name: "portfolio"
    label: "게시글"
    label_singular: "게시글"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - label: "카테고리 (해당하는 항목 모두 선택)"
        name: "overview_category"
        widget: "select"
        multiple: true
        options:
          - "시공"
          - "백화점 쇼핑몰"
          - "팝업(POP-UP)"
          - "전시 컨벤션"
          - "방송 촬영"
          - "행사 이벤트"
          - "콘서트"
          - "유지보수"
          - "제품 유통"
        required: false
      - { label: "클라이언트 (선택)", name: "client", widget: "string", required: false }
      - { label: "장소 (선택)", name: "location", widget: "string", required: false }
      - { label: "대표 이미지", name: "cover_image", widget: "image" }
      - label: "추가 사진 (선택)"
        name: "gallery"
        widget: "list"
        field: { label: "이미지", name: "image", widget: "image" }
        required: false
      - label: "상세 설명"
        name: "body"
        widget: "markdown"
        modes: ["rich_text", "raw"]
